/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// MksPipelineListerExpansion allows custom methods to be added to
// MksPipelineLister.
type MksPipelineListerExpansion interface{}

// MksPipelineNamespaceListerExpansion allows custom methods to be added to
// MksPipelineNamespaceLister.
type MksPipelineNamespaceListerExpansion interface{}

// MksPipelineRunListerExpansion allows custom methods to be added to
// MksPipelineRunLister.
type MksPipelineRunListerExpansion interface{}

// MksPipelineRunNamespaceListerExpansion allows custom methods to be added to
// MksPipelineRunNamespaceLister.
type MksPipelineRunNamespaceListerExpansion interface{}

// MksTaskListerExpansion allows custom methods to be added to
// MksTaskLister.
type MksTaskListerExpansion interface{}

// MksTaskNamespaceListerExpansion allows custom methods to be added to
// MksTaskNamespaceLister.
type MksTaskNamespaceListerExpansion interface{}

// MksTaskRunListerExpansion allows custom methods to be added to
// MksTaskRunLister.
type MksTaskRunListerExpansion interface{}

// MksTaskRunNamespaceListerExpansion allows custom methods to be added to
// MksTaskRunNamespaceLister.
type MksTaskRunNamespaceListerExpansion interface{}
