/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/MiniTeks/mks-server/pkg/apis/mkscontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMksTaskRuns implements MksTaskRunInterface
type FakeMksTaskRuns struct {
	Fake *FakeMkscontrollerV1alpha1
	ns   string
}

var mkstaskrunsResource = schema.GroupVersionResource{Group: "mkscontroller.example.mks", Version: "v1alpha1", Resource: "mkstaskruns"}

var mkstaskrunsKind = schema.GroupVersionKind{Group: "mkscontroller.example.mks", Version: "v1alpha1", Kind: "MksTaskRun"}

// Get takes name of the mksTaskRun, and returns the corresponding mksTaskRun object, and an error if there is any.
func (c *FakeMksTaskRuns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MksTaskRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mkstaskrunsResource, c.ns, name), &v1alpha1.MksTaskRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MksTaskRun), err
}

// List takes label and field selectors, and returns the list of MksTaskRuns that match those selectors.
func (c *FakeMksTaskRuns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MksTaskRunList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mkstaskrunsResource, mkstaskrunsKind, c.ns, opts), &v1alpha1.MksTaskRunList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MksTaskRunList{ListMeta: obj.(*v1alpha1.MksTaskRunList).ListMeta}
	for _, item := range obj.(*v1alpha1.MksTaskRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mksTaskRuns.
func (c *FakeMksTaskRuns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mkstaskrunsResource, c.ns, opts))

}

// Create takes the representation of a mksTaskRun and creates it.  Returns the server's representation of the mksTaskRun, and an error, if there is any.
func (c *FakeMksTaskRuns) Create(ctx context.Context, mksTaskRun *v1alpha1.MksTaskRun, opts v1.CreateOptions) (result *v1alpha1.MksTaskRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mkstaskrunsResource, c.ns, mksTaskRun), &v1alpha1.MksTaskRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MksTaskRun), err
}

// Update takes the representation of a mksTaskRun and updates it. Returns the server's representation of the mksTaskRun, and an error, if there is any.
func (c *FakeMksTaskRuns) Update(ctx context.Context, mksTaskRun *v1alpha1.MksTaskRun, opts v1.UpdateOptions) (result *v1alpha1.MksTaskRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mkstaskrunsResource, c.ns, mksTaskRun), &v1alpha1.MksTaskRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MksTaskRun), err
}

// Delete takes name of the mksTaskRun and deletes it. Returns an error if one occurs.
func (c *FakeMksTaskRuns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mkstaskrunsResource, c.ns, name, opts), &v1alpha1.MksTaskRun{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMksTaskRuns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mkstaskrunsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MksTaskRunList{})
	return err
}

// Patch applies the patch and returns the patched mksTaskRun.
func (c *FakeMksTaskRuns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MksTaskRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mkstaskrunsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MksTaskRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MksTaskRun), err
}
