/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/MiniTeks/mks-server/pkg/apis/mkscontroller/v1alpha1"
	scheme "github.com/MiniTeks/mks-server/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MksPipelineRunsGetter has a method to return a MksPipelineRunInterface.
// A group's client should implement this interface.
type MksPipelineRunsGetter interface {
	MksPipelineRuns(namespace string) MksPipelineRunInterface
}

// MksPipelineRunInterface has methods to work with MksPipelineRun resources.
type MksPipelineRunInterface interface {
	Create(ctx context.Context, mksPipelineRun *v1alpha1.MksPipelineRun, opts v1.CreateOptions) (*v1alpha1.MksPipelineRun, error)
	Update(ctx context.Context, mksPipelineRun *v1alpha1.MksPipelineRun, opts v1.UpdateOptions) (*v1alpha1.MksPipelineRun, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MksPipelineRun, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MksPipelineRunList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MksPipelineRun, err error)
	MksPipelineRunExpansion
}

// mksPipelineRuns implements MksPipelineRunInterface
type mksPipelineRuns struct {
	client rest.Interface
	ns     string
}

// newMksPipelineRuns returns a MksPipelineRuns
func newMksPipelineRuns(c *MkscontrollerV1alpha1Client, namespace string) *mksPipelineRuns {
	return &mksPipelineRuns{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mksPipelineRun, and returns the corresponding mksPipelineRun object, and an error if there is any.
func (c *mksPipelineRuns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MksPipelineRun, err error) {
	result = &v1alpha1.MksPipelineRun{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mkspipelineruns").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MksPipelineRuns that match those selectors.
func (c *mksPipelineRuns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MksPipelineRunList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MksPipelineRunList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mkspipelineruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mksPipelineRuns.
func (c *mksPipelineRuns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mkspipelineruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mksPipelineRun and creates it.  Returns the server's representation of the mksPipelineRun, and an error, if there is any.
func (c *mksPipelineRuns) Create(ctx context.Context, mksPipelineRun *v1alpha1.MksPipelineRun, opts v1.CreateOptions) (result *v1alpha1.MksPipelineRun, err error) {
	result = &v1alpha1.MksPipelineRun{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mkspipelineruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mksPipelineRun).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mksPipelineRun and updates it. Returns the server's representation of the mksPipelineRun, and an error, if there is any.
func (c *mksPipelineRuns) Update(ctx context.Context, mksPipelineRun *v1alpha1.MksPipelineRun, opts v1.UpdateOptions) (result *v1alpha1.MksPipelineRun, err error) {
	result = &v1alpha1.MksPipelineRun{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mkspipelineruns").
		Name(mksPipelineRun.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mksPipelineRun).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mksPipelineRun and deletes it. Returns an error if one occurs.
func (c *mksPipelineRuns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mkspipelineruns").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mksPipelineRuns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mkspipelineruns").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mksPipelineRun.
func (c *mksPipelineRuns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MksPipelineRun, err error) {
	result = &v1alpha1.MksPipelineRun{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mkspipelineruns").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
