/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/MiniTeks/mks-server/pkg/apis/mkscontroller/v1alpha1"
	scheme "github.com/MiniTeks/mks-server/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MksTaskRunsGetter has a method to return a MksTaskRunInterface.
// A group's client should implement this interface.
type MksTaskRunsGetter interface {
	MksTaskRuns(namespace string) MksTaskRunInterface
}

// MksTaskRunInterface has methods to work with MksTaskRun resources.
type MksTaskRunInterface interface {
	Create(ctx context.Context, mksTaskRun *v1alpha1.MksTaskRun, opts v1.CreateOptions) (*v1alpha1.MksTaskRun, error)
	Update(ctx context.Context, mksTaskRun *v1alpha1.MksTaskRun, opts v1.UpdateOptions) (*v1alpha1.MksTaskRun, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MksTaskRun, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MksTaskRunList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MksTaskRun, err error)
	MksTaskRunExpansion
}

// mksTaskRuns implements MksTaskRunInterface
type mksTaskRuns struct {
	client rest.Interface
	ns     string
}

// newMksTaskRuns returns a MksTaskRuns
func newMksTaskRuns(c *MkscontrollerV1alpha1Client, namespace string) *mksTaskRuns {
	return &mksTaskRuns{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mksTaskRun, and returns the corresponding mksTaskRun object, and an error if there is any.
func (c *mksTaskRuns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MksTaskRun, err error) {
	result = &v1alpha1.MksTaskRun{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mkstaskruns").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MksTaskRuns that match those selectors.
func (c *mksTaskRuns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MksTaskRunList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MksTaskRunList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mkstaskruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mksTaskRuns.
func (c *mksTaskRuns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mkstaskruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mksTaskRun and creates it.  Returns the server's representation of the mksTaskRun, and an error, if there is any.
func (c *mksTaskRuns) Create(ctx context.Context, mksTaskRun *v1alpha1.MksTaskRun, opts v1.CreateOptions) (result *v1alpha1.MksTaskRun, err error) {
	result = &v1alpha1.MksTaskRun{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mkstaskruns").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mksTaskRun).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mksTaskRun and updates it. Returns the server's representation of the mksTaskRun, and an error, if there is any.
func (c *mksTaskRuns) Update(ctx context.Context, mksTaskRun *v1alpha1.MksTaskRun, opts v1.UpdateOptions) (result *v1alpha1.MksTaskRun, err error) {
	result = &v1alpha1.MksTaskRun{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mkstaskruns").
		Name(mksTaskRun.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mksTaskRun).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mksTaskRun and deletes it. Returns an error if one occurs.
func (c *mksTaskRuns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mkstaskruns").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mksTaskRuns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mkstaskruns").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mksTaskRun.
func (c *mksTaskRuns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MksTaskRun, err error) {
	result = &v1alpha1.MksTaskRun{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mkstaskruns").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
